# docker-compose.yaml file for valhalla-link project

version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_PROTOCOL=${PROTOCOL}
      - SERVER_HOST=${HOST}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_CLIENT_PORT=${CLIENT_PORT}
      - VITE_SERVER_URL=${SERVER_URL}
    depends_on:
      - server
    networks:
      - app-network

volumes:
  mysql-data: